# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='search.proto',
  package='landmark.search',
  syntax='proto3',
  serialized_options=b'Z\021./landmark_search',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csearch.proto\x12\x0flandmark.search\".\n\x12\x41\x64\x64LandmarkRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x15\n\x13\x41\x64\x64LandmarkResponse\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"5\n\x0eSearchResponse\x12\x13\n\x0blandmarkIds\x18\x01 \x03(\t\x12\x0e\n\x06tagIds\x18\x02 \x03(\t2\xb9\x01\n\x0eLandmarkSearch\x12Z\n\x0b\x41\x64\x64Landmark\x12#.landmark.search.AddLandmarkRequest\x1a$.landmark.search.AddLandmarkResponse\"\x00\x12K\n\x06Search\x12\x1e.landmark.search.SearchRequest\x1a\x1f.landmark.search.SearchResponse\"\x00\x42\x13Z\x11./landmark_searchb\x06proto3'
)




_ADDLANDMARKREQUEST = _descriptor.Descriptor(
  name='AddLandmarkRequest',
  full_name='landmark.search.AddLandmarkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='landmark.search.AddLandmarkRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='landmark.search.AddLandmarkRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=79,
)


_ADDLANDMARKRESPONSE = _descriptor.Descriptor(
  name='AddLandmarkResponse',
  full_name='landmark.search.AddLandmarkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=102,
)


_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='landmark.search.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='landmark.search.SearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=134,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
  name='SearchResponse',
  full_name='landmark.search.SearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='landmarkIds', full_name='landmark.search.SearchResponse.landmarkIds', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tagIds', full_name='landmark.search.SearchResponse.tagIds', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['AddLandmarkRequest'] = _ADDLANDMARKREQUEST
DESCRIPTOR.message_types_by_name['AddLandmarkResponse'] = _ADDLANDMARKRESPONSE
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchResponse'] = _SEARCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddLandmarkRequest = _reflection.GeneratedProtocolMessageType('AddLandmarkRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDLANDMARKREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:landmark.search.AddLandmarkRequest)
  })
_sym_db.RegisterMessage(AddLandmarkRequest)

AddLandmarkResponse = _reflection.GeneratedProtocolMessageType('AddLandmarkResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDLANDMARKRESPONSE,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:landmark.search.AddLandmarkResponse)
  })
_sym_db.RegisterMessage(AddLandmarkResponse)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:landmark.search.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:landmark.search.SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)


DESCRIPTOR._options = None

_LANDMARKSEARCH = _descriptor.ServiceDescriptor(
  name='LandmarkSearch',
  full_name='landmark.search.LandmarkSearch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=192,
  serialized_end=377,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddLandmark',
    full_name='landmark.search.LandmarkSearch.AddLandmark',
    index=0,
    containing_service=None,
    input_type=_ADDLANDMARKREQUEST,
    output_type=_ADDLANDMARKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='landmark.search.LandmarkSearch.Search',
    index=1,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LANDMARKSEARCH)

DESCRIPTOR.services_by_name['LandmarkSearch'] = _LANDMARKSEARCH

# @@protoc_insertion_point(module_scope)
