# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x0flandmark.search\".\n\x12\x41\x64\x64LandmarkRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x15\n\x13\x41\x64\x64LandmarkResponse\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"5\n\x0eSearchResponse\x12\x13\n\x0blandmarkIds\x18\x01 \x03(\t\x12\x0e\n\x06tagIds\x18\x02 \x03(\t2\xb9\x01\n\x0eLandmarkSearch\x12Z\n\x0b\x41\x64\x64Landmark\x12#.landmark.search.AddLandmarkRequest\x1a$.landmark.search.AddLandmarkResponse\"\x00\x12K\n\x06Search\x12\x1e.landmark.search.SearchRequest\x1a\x1f.landmark.search.SearchResponse\"\x00\x42\x13Z\x11./landmark_searchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021./landmark_search'
  _globals['_ADDLANDMARKREQUEST']._serialized_start=33
  _globals['_ADDLANDMARKREQUEST']._serialized_end=79
  _globals['_ADDLANDMARKRESPONSE']._serialized_start=81
  _globals['_ADDLANDMARKRESPONSE']._serialized_end=102
  _globals['_SEARCHREQUEST']._serialized_start=104
  _globals['_SEARCHREQUEST']._serialized_end=134
  _globals['_SEARCHRESPONSE']._serialized_start=136
  _globals['_SEARCHRESPONSE']._serialized_end=189
  _globals['_LANDMARKSEARCH']._serialized_start=192
  _globals['_LANDMARKSEARCH']._serialized_end=377
# @@protoc_insertion_point(module_scope)
