# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import search_pb2 as search__pb2


class LandmarkSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddLandmark = channel.unary_unary(
                '/landmark.search.LandmarkSearch/AddLandmark',
                request_serializer=search__pb2.AddLandmarkRequest.SerializeToString,
                response_deserializer=search__pb2.AddLandmarkResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/landmark.search.LandmarkSearch/Search',
                request_serializer=search__pb2.SearchRequest.SerializeToString,
                response_deserializer=search__pb2.SearchResponse.FromString,
                )


class LandmarkSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddLandmark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LandmarkSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddLandmark': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLandmark,
                    request_deserializer=search__pb2.AddLandmarkRequest.FromString,
                    response_serializer=search__pb2.AddLandmarkResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=search__pb2.SearchRequest.FromString,
                    response_serializer=search__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'landmark.search.LandmarkSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LandmarkSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddLandmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/landmark.search.LandmarkSearch/AddLandmark',
            search__pb2.AddLandmarkRequest.SerializeToString,
            search__pb2.AddLandmarkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/landmark.search.LandmarkSearch/Search',
            search__pb2.SearchRequest.SerializeToString,
            search__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
